### ISSUE TITLE
GDEY075Z08 requires DESPI-C02 RESE to be set at '3'

### ISSUE THREAD

**Issue by jdeluyck** [lmarzen/esp32-weather-epd#104]
I've just assembled everything using an GDEY075Z08 board, a DESPI-C02, and I was wondering why I couldn't get any display output.

After switching the RESE switch to 3, the display came to life. Maybe the info can be updated to reflect this?

**Comment by lmarzen** [comment]
Hmmm... I don't have that specific panel, so it's hard for me to confirm, but every place I check says otherwise.

See this video from GoodDisplay demonstrating the hardware working with 0.47R https://www.buy-lcd.com/products/75-e-paper-display-spi-color-electronic-paper-screen-with-epd-hat-gdey075z08despi-c02

See section _4.2 RESE resistor selection of DESPI-C02_ of the E-Paper Display Evaluation Kit by Good Display
https://v4.cecdn.yun300.cn/100001_1909185148/E-Paper%20Display%20Evalution%20Kit%20for%20ESP8266.pdf
