### ISSUE TITLE
Is there a way to run it with Arduino that is not platformio based?

### ISSUE THREAD

**Issue by PaekHyun** [lmarzen/esp32-weather-epd#112]
Is there a way to run it with Arduino that is not platformio based?
The esp32-c6 I have is not supported by platformio, so I cannot debug it.

**Comment by lmarzen** [comment]
I'm sure with enough work you could get it to compile with the Arduino IDE, but I can't help you with that. If the board you mentioned has support for the Arduino IDE, it would be easier to add it to Platformio, since the configs for most esp32 boards are directly based off the Arduino IDE files for the board.

To add support for the board officially, you need to make pull requests to these two repositories. If you don't feel up to that, there is definitely a way to use a custom voard config from arduino ide with platformio.
https://github.com/platformio/platform-espressif32/
https://github.com/espressif/arduino-esp32/
